// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages_pld.proto
// Protobuf C++ Version: 6.31.1

#ifndef messages_5fpld_2eproto_2epb_2eh
#define messages_5fpld_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_messages_5fpld_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_5fpld_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_messages_5fpld_2eproto;
}  // extern "C"
class PlannerResponse;
struct PlannerResponseDefaultTypeInternal;
extern PlannerResponseDefaultTypeInternal _PlannerResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PlannerResponse_class_data_;
class PlannerResponseList;
struct PlannerResponseListDefaultTypeInternal;
extern PlannerResponseListDefaultTypeInternal _PlannerResponseList_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PlannerResponseList_class_data_;
class Status;
struct StatusDefaultTypeInternal;
extern StatusDefaultTypeInternal _Status_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Status_class_data_;
class WrapperDrone;
struct WrapperDroneDefaultTypeInternal;
extern WrapperDroneDefaultTypeInternal _WrapperDrone_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull WrapperDrone_class_data_;
class WrapperPlanner;
struct WrapperPlannerDefaultTypeInternal;
extern WrapperPlannerDefaultTypeInternal _WrapperPlanner_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull WrapperPlanner_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Status final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Status) */ {
 public:
  inline Status() : Status(nullptr) {}
  ~Status() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Status* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Status));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Status(::google::protobuf::internal::ConstantInitialized);

  inline Status(const Status& from) : Status(nullptr, from) {}
  inline Status(Status&& from) noexcept
      : Status(nullptr, ::std::move(from)) {}
  inline Status& operator=(const Status& from) {
    CopyFrom(from);
    return *this;
  }
  inline Status& operator=(Status&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Status& default_instance() {
    return *reinterpret_cast<const Status*>(
        &_Status_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(Status& a, Status& b) { a.Swap(&b); }
  inline void Swap(Status* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Status* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Status* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Status>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Status& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Status& from) { Status::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Status* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Status"; }

 protected:
  explicit Status(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Status(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Status& from);
  Status(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Status&& from) noexcept
      : Status(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypeStatusFieldNumber = 1,
  };
  // string type_status = 1;
  void clear_type_status() ;
  const ::std::string& type_status() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_type_status(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_type_status();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_type_status();
  void set_allocated_type_status(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_type_status() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_type_status(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_type_status();

  public:
  // @@protoc_insertion_point(class_scope:Status)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 26,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Status& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr type_status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_5fpld_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Status_class_data_;
// -------------------------------------------------------------------

class PlannerResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PlannerResponse) */ {
 public:
  inline PlannerResponse() : PlannerResponse(nullptr) {}
  ~PlannerResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlannerResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlannerResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlannerResponse(::google::protobuf::internal::ConstantInitialized);

  inline PlannerResponse(const PlannerResponse& from) : PlannerResponse(nullptr, from) {}
  inline PlannerResponse(PlannerResponse&& from) noexcept
      : PlannerResponse(nullptr, ::std::move(from)) {}
  inline PlannerResponse& operator=(const PlannerResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlannerResponse& operator=(PlannerResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlannerResponse& default_instance() {
    return *reinterpret_cast<const PlannerResponse*>(
        &_PlannerResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(PlannerResponse& a, PlannerResponse& b) { a.Swap(&b); }
  inline void Swap(PlannerResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlannerResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlannerResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlannerResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlannerResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlannerResponse& from) { PlannerResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlannerResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PlannerResponse"; }

 protected:
  explicit PlannerResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PlannerResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlannerResponse& from);
  PlannerResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PlannerResponse&& from) noexcept
      : PlannerResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLonFieldNumber = 1,
    kLatFieldNumber = 2,
  };
  // repeated double lon = 1;
  int lon_size() const;
  private:
  int _internal_lon_size() const;

  public:
  void clear_lon() ;
  double lon(int index) const;
  void set_lon(int index, double value);
  void add_lon(double value);
  const ::google::protobuf::RepeatedField<double>& lon() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_lon();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_lon() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_lon();

  public:
  // repeated double lat = 2;
  int lat_size() const;
  private:
  int _internal_lat_size() const;

  public:
  void clear_lat() ;
  double lat(int index) const;
  void set_lat(int index, double value);
  void add_lat(double value);
  const ::google::protobuf::RepeatedField<double>& lat() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_lat();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_lat() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_lat();

  public:
  // @@protoc_insertion_point(class_scope:PlannerResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PlannerResponse& from_msg);
    ::google::protobuf::RepeatedField<double> lon_;
    ::google::protobuf::RepeatedField<double> lat_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_5fpld_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PlannerResponse_class_data_;
// -------------------------------------------------------------------

class WrapperDrone final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:WrapperDrone) */ {
 public:
  inline WrapperDrone() : WrapperDrone(nullptr) {}
  ~WrapperDrone() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WrapperDrone* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WrapperDrone));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WrapperDrone(::google::protobuf::internal::ConstantInitialized);

  inline WrapperDrone(const WrapperDrone& from) : WrapperDrone(nullptr, from) {}
  inline WrapperDrone(WrapperDrone&& from) noexcept
      : WrapperDrone(nullptr, ::std::move(from)) {}
  inline WrapperDrone& operator=(const WrapperDrone& from) {
    CopyFrom(from);
    return *this;
  }
  inline WrapperDrone& operator=(WrapperDrone&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WrapperDrone& default_instance() {
    return *reinterpret_cast<const WrapperDrone*>(
        &_WrapperDrone_default_instance_);
  }
  enum PayloadCase {
    kStatus = 1,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(WrapperDrone& a, WrapperDrone& b) { a.Swap(&b); }
  inline void Swap(WrapperDrone* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WrapperDrone* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WrapperDrone* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WrapperDrone>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WrapperDrone& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WrapperDrone& from) { WrapperDrone::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WrapperDrone* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "WrapperDrone"; }

 protected:
  explicit WrapperDrone(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WrapperDrone(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WrapperDrone& from);
  WrapperDrone(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WrapperDrone&& from) noexcept
      : WrapperDrone(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
  };
  // .Status status = 1;
  bool has_status() const;
  private:
  bool _internal_has_status() const;

  public:
  void clear_status() ;
  const ::Status& status() const;
  [[nodiscard]] ::Status* PROTOBUF_NULLABLE release_status();
  ::Status* PROTOBUF_NONNULL mutable_status();
  void set_allocated_status(::Status* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_status(::Status* PROTOBUF_NULLABLE value);
  ::Status* PROTOBUF_NULLABLE unsafe_arena_release_status();

  private:
  const ::Status& _internal_status() const;
  ::Status* PROTOBUF_NONNULL _internal_mutable_status();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:WrapperDrone)
 private:
  class _Internal;
  void set_has_status();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const WrapperDrone& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::Status* PROTOBUF_NULLABLE status_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_5fpld_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull WrapperDrone_class_data_;
// -------------------------------------------------------------------

class PlannerResponseList final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PlannerResponseList) */ {
 public:
  inline PlannerResponseList() : PlannerResponseList(nullptr) {}
  ~PlannerResponseList() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlannerResponseList* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlannerResponseList));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlannerResponseList(::google::protobuf::internal::ConstantInitialized);

  inline PlannerResponseList(const PlannerResponseList& from) : PlannerResponseList(nullptr, from) {}
  inline PlannerResponseList(PlannerResponseList&& from) noexcept
      : PlannerResponseList(nullptr, ::std::move(from)) {}
  inline PlannerResponseList& operator=(const PlannerResponseList& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlannerResponseList& operator=(PlannerResponseList&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlannerResponseList& default_instance() {
    return *reinterpret_cast<const PlannerResponseList*>(
        &_PlannerResponseList_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PlannerResponseList& a, PlannerResponseList& b) { a.Swap(&b); }
  inline void Swap(PlannerResponseList* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlannerResponseList* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlannerResponseList* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlannerResponseList>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlannerResponseList& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlannerResponseList& from) { PlannerResponseList::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlannerResponseList* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PlannerResponseList"; }

 protected:
  explicit PlannerResponseList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PlannerResponseList(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlannerResponseList& from);
  PlannerResponseList(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PlannerResponseList&& from) noexcept
      : PlannerResponseList(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kItemsFieldNumber = 1,
  };
  // repeated .PlannerResponse items = 1;
  int items_size() const;
  private:
  int _internal_items_size() const;

  public:
  void clear_items() ;
  ::PlannerResponse* PROTOBUF_NONNULL mutable_items(int index);
  ::google::protobuf::RepeatedPtrField<::PlannerResponse>* PROTOBUF_NONNULL mutable_items();

  private:
  const ::google::protobuf::RepeatedPtrField<::PlannerResponse>& _internal_items() const;
  ::google::protobuf::RepeatedPtrField<::PlannerResponse>* PROTOBUF_NONNULL _internal_mutable_items();
  public:
  const ::PlannerResponse& items(int index) const;
  ::PlannerResponse* PROTOBUF_NONNULL add_items();
  const ::google::protobuf::RepeatedPtrField<::PlannerResponse>& items() const;
  // @@protoc_insertion_point(class_scope:PlannerResponseList)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PlannerResponseList& from_msg);
    ::google::protobuf::RepeatedPtrField< ::PlannerResponse > items_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_5fpld_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PlannerResponseList_class_data_;
// -------------------------------------------------------------------

class WrapperPlanner final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:WrapperPlanner) */ {
 public:
  inline WrapperPlanner() : WrapperPlanner(nullptr) {}
  ~WrapperPlanner() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WrapperPlanner* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WrapperPlanner));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WrapperPlanner(::google::protobuf::internal::ConstantInitialized);

  inline WrapperPlanner(const WrapperPlanner& from) : WrapperPlanner(nullptr, from) {}
  inline WrapperPlanner(WrapperPlanner&& from) noexcept
      : WrapperPlanner(nullptr, ::std::move(from)) {}
  inline WrapperPlanner& operator=(const WrapperPlanner& from) {
    CopyFrom(from);
    return *this;
  }
  inline WrapperPlanner& operator=(WrapperPlanner&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WrapperPlanner& default_instance() {
    return *reinterpret_cast<const WrapperPlanner*>(
        &_WrapperPlanner_default_instance_);
  }
  enum PayloadCase {
    kPlannerResponse = 1,
    kStatus = 2,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(WrapperPlanner& a, WrapperPlanner& b) { a.Swap(&b); }
  inline void Swap(WrapperPlanner* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WrapperPlanner* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WrapperPlanner* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WrapperPlanner>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WrapperPlanner& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WrapperPlanner& from) { WrapperPlanner::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WrapperPlanner* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "WrapperPlanner"; }

 protected:
  explicit WrapperPlanner(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WrapperPlanner(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WrapperPlanner& from);
  WrapperPlanner(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WrapperPlanner&& from) noexcept
      : WrapperPlanner(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlannerResponseFieldNumber = 1,
    kStatusFieldNumber = 2,
  };
  // .PlannerResponseList planner_response = 1;
  bool has_planner_response() const;
  private:
  bool _internal_has_planner_response() const;

  public:
  void clear_planner_response() ;
  const ::PlannerResponseList& planner_response() const;
  [[nodiscard]] ::PlannerResponseList* PROTOBUF_NULLABLE release_planner_response();
  ::PlannerResponseList* PROTOBUF_NONNULL mutable_planner_response();
  void set_allocated_planner_response(::PlannerResponseList* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_planner_response(::PlannerResponseList* PROTOBUF_NULLABLE value);
  ::PlannerResponseList* PROTOBUF_NULLABLE unsafe_arena_release_planner_response();

  private:
  const ::PlannerResponseList& _internal_planner_response() const;
  ::PlannerResponseList* PROTOBUF_NONNULL _internal_mutable_planner_response();

  public:
  // .Status status = 2;
  bool has_status() const;
  private:
  bool _internal_has_status() const;

  public:
  void clear_status() ;
  const ::Status& status() const;
  [[nodiscard]] ::Status* PROTOBUF_NULLABLE release_status();
  ::Status* PROTOBUF_NONNULL mutable_status();
  void set_allocated_status(::Status* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_status(::Status* PROTOBUF_NULLABLE value);
  ::Status* PROTOBUF_NULLABLE unsafe_arena_release_status();

  private:
  const ::Status& _internal_status() const;
  ::Status* PROTOBUF_NONNULL _internal_mutable_status();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:WrapperPlanner)
 private:
  class _Internal;
  void set_has_planner_response();
  void set_has_status();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const WrapperPlanner& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::PlannerResponseList* PROTOBUF_NULLABLE planner_response_;
      ::Status* PROTOBUF_NULLABLE status_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_5fpld_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull WrapperPlanner_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// WrapperPlanner

// .PlannerResponseList planner_response = 1;
inline bool WrapperPlanner::has_planner_response() const {
  return payload_case() == kPlannerResponse;
}
inline bool WrapperPlanner::_internal_has_planner_response() const {
  return payload_case() == kPlannerResponse;
}
inline void WrapperPlanner::set_has_planner_response() {
  _impl_._oneof_case_[0] = kPlannerResponse;
}
inline void WrapperPlanner::clear_planner_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kPlannerResponse) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.planner_response_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.planner_response_);
    }
    clear_has_payload();
  }
}
inline ::PlannerResponseList* PROTOBUF_NULLABLE WrapperPlanner::release_planner_response() {
  // @@protoc_insertion_point(field_release:WrapperPlanner.planner_response)
  if (payload_case() == kPlannerResponse) {
    clear_has_payload();
    auto* temp = _impl_.payload_.planner_response_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.planner_response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PlannerResponseList& WrapperPlanner::_internal_planner_response() const {
  return payload_case() == kPlannerResponse ? *_impl_.payload_.planner_response_ : reinterpret_cast<::PlannerResponseList&>(::_PlannerResponseList_default_instance_);
}
inline const ::PlannerResponseList& WrapperPlanner::planner_response() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:WrapperPlanner.planner_response)
  return _internal_planner_response();
}
inline ::PlannerResponseList* PROTOBUF_NULLABLE WrapperPlanner::unsafe_arena_release_planner_response() {
  // @@protoc_insertion_point(field_unsafe_arena_release:WrapperPlanner.planner_response)
  if (payload_case() == kPlannerResponse) {
    clear_has_payload();
    auto* temp = _impl_.payload_.planner_response_;
    _impl_.payload_.planner_response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void WrapperPlanner::unsafe_arena_set_allocated_planner_response(
    ::PlannerResponseList* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_planner_response();
    _impl_.payload_.planner_response_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:WrapperPlanner.planner_response)
}
inline ::PlannerResponseList* PROTOBUF_NONNULL WrapperPlanner::_internal_mutable_planner_response() {
  if (payload_case() != kPlannerResponse) {
    clear_payload();
    set_has_planner_response();
    _impl_.payload_.planner_response_ = 
        ::google::protobuf::Message::DefaultConstruct<::PlannerResponseList>(GetArena());
  }
  return _impl_.payload_.planner_response_;
}
inline ::PlannerResponseList* PROTOBUF_NONNULL WrapperPlanner::mutable_planner_response()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::PlannerResponseList* _msg = _internal_mutable_planner_response();
  // @@protoc_insertion_point(field_mutable:WrapperPlanner.planner_response)
  return _msg;
}

// .Status status = 2;
inline bool WrapperPlanner::has_status() const {
  return payload_case() == kStatus;
}
inline bool WrapperPlanner::_internal_has_status() const {
  return payload_case() == kStatus;
}
inline void WrapperPlanner::set_has_status() {
  _impl_._oneof_case_[0] = kStatus;
}
inline void WrapperPlanner::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kStatus) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.status_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.status_);
    }
    clear_has_payload();
  }
}
inline ::Status* PROTOBUF_NULLABLE WrapperPlanner::release_status() {
  // @@protoc_insertion_point(field_release:WrapperPlanner.status)
  if (payload_case() == kStatus) {
    clear_has_payload();
    auto* temp = _impl_.payload_.status_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Status& WrapperPlanner::_internal_status() const {
  return payload_case() == kStatus ? *_impl_.payload_.status_ : reinterpret_cast<::Status&>(::_Status_default_instance_);
}
inline const ::Status& WrapperPlanner::status() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:WrapperPlanner.status)
  return _internal_status();
}
inline ::Status* PROTOBUF_NULLABLE WrapperPlanner::unsafe_arena_release_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:WrapperPlanner.status)
  if (payload_case() == kStatus) {
    clear_has_payload();
    auto* temp = _impl_.payload_.status_;
    _impl_.payload_.status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void WrapperPlanner::unsafe_arena_set_allocated_status(
    ::Status* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_status();
    _impl_.payload_.status_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:WrapperPlanner.status)
}
inline ::Status* PROTOBUF_NONNULL WrapperPlanner::_internal_mutable_status() {
  if (payload_case() != kStatus) {
    clear_payload();
    set_has_status();
    _impl_.payload_.status_ = 
        ::google::protobuf::Message::DefaultConstruct<::Status>(GetArena());
  }
  return _impl_.payload_.status_;
}
inline ::Status* PROTOBUF_NONNULL WrapperPlanner::mutable_status()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Status* _msg = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:WrapperPlanner.status)
  return _msg;
}

inline bool WrapperPlanner::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void WrapperPlanner::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline WrapperPlanner::PayloadCase WrapperPlanner::payload_case() const {
  return WrapperPlanner::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// WrapperDrone

// .Status status = 1;
inline bool WrapperDrone::has_status() const {
  return payload_case() == kStatus;
}
inline bool WrapperDrone::_internal_has_status() const {
  return payload_case() == kStatus;
}
inline void WrapperDrone::set_has_status() {
  _impl_._oneof_case_[0] = kStatus;
}
inline void WrapperDrone::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kStatus) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.status_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.status_);
    }
    clear_has_payload();
  }
}
inline ::Status* PROTOBUF_NULLABLE WrapperDrone::release_status() {
  // @@protoc_insertion_point(field_release:WrapperDrone.status)
  if (payload_case() == kStatus) {
    clear_has_payload();
    auto* temp = _impl_.payload_.status_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Status& WrapperDrone::_internal_status() const {
  return payload_case() == kStatus ? *_impl_.payload_.status_ : reinterpret_cast<::Status&>(::_Status_default_instance_);
}
inline const ::Status& WrapperDrone::status() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:WrapperDrone.status)
  return _internal_status();
}
inline ::Status* PROTOBUF_NULLABLE WrapperDrone::unsafe_arena_release_status() {
  // @@protoc_insertion_point(field_unsafe_arena_release:WrapperDrone.status)
  if (payload_case() == kStatus) {
    clear_has_payload();
    auto* temp = _impl_.payload_.status_;
    _impl_.payload_.status_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void WrapperDrone::unsafe_arena_set_allocated_status(
    ::Status* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_status();
    _impl_.payload_.status_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:WrapperDrone.status)
}
inline ::Status* PROTOBUF_NONNULL WrapperDrone::_internal_mutable_status() {
  if (payload_case() != kStatus) {
    clear_payload();
    set_has_status();
    _impl_.payload_.status_ = 
        ::google::protobuf::Message::DefaultConstruct<::Status>(GetArena());
  }
  return _impl_.payload_.status_;
}
inline ::Status* PROTOBUF_NONNULL WrapperDrone::mutable_status()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Status* _msg = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:WrapperDrone.status)
  return _msg;
}

inline bool WrapperDrone::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void WrapperDrone::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline WrapperDrone::PayloadCase WrapperDrone::payload_case() const {
  return WrapperDrone::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// PlannerResponseList

// repeated .PlannerResponse items = 1;
inline int PlannerResponseList::_internal_items_size() const {
  return _internal_items().size();
}
inline int PlannerResponseList::items_size() const {
  return _internal_items_size();
}
inline void PlannerResponseList::clear_items() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.items_.Clear();
}
inline ::PlannerResponse* PROTOBUF_NONNULL PlannerResponseList::mutable_items(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:PlannerResponseList.items)
  return _internal_mutable_items()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::PlannerResponse>* PROTOBUF_NONNULL PlannerResponseList::mutable_items()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:PlannerResponseList.items)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_items();
}
inline const ::PlannerResponse& PlannerResponseList::items(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PlannerResponseList.items)
  return _internal_items().Get(index);
}
inline ::PlannerResponse* PROTOBUF_NONNULL PlannerResponseList::add_items()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::PlannerResponse* _add = _internal_mutable_items()->Add();
  // @@protoc_insertion_point(field_add:PlannerResponseList.items)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::PlannerResponse>& PlannerResponseList::items() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:PlannerResponseList.items)
  return _internal_items();
}
inline const ::google::protobuf::RepeatedPtrField<::PlannerResponse>&
PlannerResponseList::_internal_items() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.items_;
}
inline ::google::protobuf::RepeatedPtrField<::PlannerResponse>* PROTOBUF_NONNULL
PlannerResponseList::_internal_mutable_items() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.items_;
}

// -------------------------------------------------------------------

// PlannerResponse

// repeated double lon = 1;
inline int PlannerResponse::_internal_lon_size() const {
  return _internal_lon().size();
}
inline int PlannerResponse::lon_size() const {
  return _internal_lon_size();
}
inline void PlannerResponse::clear_lon() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lon_.Clear();
}
inline double PlannerResponse::lon(int index) const {
  // @@protoc_insertion_point(field_get:PlannerResponse.lon)
  return _internal_lon().Get(index);
}
inline void PlannerResponse::set_lon(int index, double value) {
  _internal_mutable_lon()->Set(index, value);
  // @@protoc_insertion_point(field_set:PlannerResponse.lon)
}
inline void PlannerResponse::add_lon(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_lon()->Add(value);
  // @@protoc_insertion_point(field_add:PlannerResponse.lon)
}
inline const ::google::protobuf::RepeatedField<double>& PlannerResponse::lon() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:PlannerResponse.lon)
  return _internal_lon();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL PlannerResponse::mutable_lon()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:PlannerResponse.lon)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_lon();
}
inline const ::google::protobuf::RepeatedField<double>&
PlannerResponse::_internal_lon() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lon_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
PlannerResponse::_internal_mutable_lon() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.lon_;
}

// repeated double lat = 2;
inline int PlannerResponse::_internal_lat_size() const {
  return _internal_lat().size();
}
inline int PlannerResponse::lat_size() const {
  return _internal_lat_size();
}
inline void PlannerResponse::clear_lat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lat_.Clear();
}
inline double PlannerResponse::lat(int index) const {
  // @@protoc_insertion_point(field_get:PlannerResponse.lat)
  return _internal_lat().Get(index);
}
inline void PlannerResponse::set_lat(int index, double value) {
  _internal_mutable_lat()->Set(index, value);
  // @@protoc_insertion_point(field_set:PlannerResponse.lat)
}
inline void PlannerResponse::add_lat(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_lat()->Add(value);
  // @@protoc_insertion_point(field_add:PlannerResponse.lat)
}
inline const ::google::protobuf::RepeatedField<double>& PlannerResponse::lat() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:PlannerResponse.lat)
  return _internal_lat();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL PlannerResponse::mutable_lat()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:PlannerResponse.lat)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_lat();
}
inline const ::google::protobuf::RepeatedField<double>&
PlannerResponse::_internal_lat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lat_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
PlannerResponse::_internal_mutable_lat() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.lat_;
}

// -------------------------------------------------------------------

// Status

// string type_status = 1;
inline void Status::clear_type_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_status_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& Status::type_status() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Status.type_status)
  return _internal_type_status();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Status::set_type_status(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.type_status_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Status.type_status)
}
inline ::std::string* PROTOBUF_NONNULL Status::mutable_type_status()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_type_status();
  // @@protoc_insertion_point(field_mutable:Status.type_status)
  return _s;
}
inline const ::std::string& Status::_internal_type_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_status_.Get();
}
inline void Status::_internal_set_type_status(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.type_status_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Status::_internal_mutable_type_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.type_status_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Status::release_type_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Status.type_status)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.type_status_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.type_status_.Set("", GetArena());
  }
  return released;
}
inline void Status::set_allocated_type_status(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.type_status_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.type_status_.IsDefault()) {
    _impl_.type_status_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Status.type_status)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // messages_5fpld_2eproto_2epb_2eh
