// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages_drone.proto
// Protobuf C++ Version: 6.31.1

#ifndef messages_5fdrone_2eproto_2epb_2eh
#define messages_5fdrone_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_messages_5fdrone_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_5fdrone_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_messages_5fdrone_2eproto;
}  // extern "C"
class DroneCommand;
struct DroneCommandDefaultTypeInternal;
extern DroneCommandDefaultTypeInternal _DroneCommand_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DroneCommand_class_data_;
class WrapperDroneCommand;
struct WrapperDroneCommandDefaultTypeInternal;
extern WrapperDroneCommandDefaultTypeInternal _WrapperDroneCommand_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull WrapperDroneCommand_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class DroneCommand final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DroneCommand) */ {
 public:
  inline DroneCommand() : DroneCommand(nullptr) {}
  ~DroneCommand() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DroneCommand* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DroneCommand));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DroneCommand(::google::protobuf::internal::ConstantInitialized);

  inline DroneCommand(const DroneCommand& from) : DroneCommand(nullptr, from) {}
  inline DroneCommand(DroneCommand&& from) noexcept
      : DroneCommand(nullptr, ::std::move(from)) {}
  inline DroneCommand& operator=(const DroneCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline DroneCommand& operator=(DroneCommand&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DroneCommand& default_instance() {
    return *reinterpret_cast<const DroneCommand*>(
        &_DroneCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(DroneCommand& a, DroneCommand& b) { a.Swap(&b); }
  inline void Swap(DroneCommand* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DroneCommand* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DroneCommand* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DroneCommand>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DroneCommand& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DroneCommand& from) { DroneCommand::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DroneCommand* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "DroneCommand"; }

 protected:
  explicit DroneCommand(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DroneCommand(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DroneCommand& from);
  DroneCommand(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DroneCommand&& from) noexcept
      : DroneCommand(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommandFieldNumber = 1,
  };
  // string command = 1;
  void clear_command() ;
  const ::std::string& command() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_command(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_command();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_command();
  void set_allocated_command(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_command() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_command(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_command();

  public:
  // @@protoc_insertion_point(class_scope:DroneCommand)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 28,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DroneCommand& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr command_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_5fdrone_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DroneCommand_class_data_;
// -------------------------------------------------------------------

class WrapperDroneCommand final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:WrapperDroneCommand) */ {
 public:
  inline WrapperDroneCommand() : WrapperDroneCommand(nullptr) {}
  ~WrapperDroneCommand() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WrapperDroneCommand* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WrapperDroneCommand));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WrapperDroneCommand(::google::protobuf::internal::ConstantInitialized);

  inline WrapperDroneCommand(const WrapperDroneCommand& from) : WrapperDroneCommand(nullptr, from) {}
  inline WrapperDroneCommand(WrapperDroneCommand&& from) noexcept
      : WrapperDroneCommand(nullptr, ::std::move(from)) {}
  inline WrapperDroneCommand& operator=(const WrapperDroneCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline WrapperDroneCommand& operator=(WrapperDroneCommand&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WrapperDroneCommand& default_instance() {
    return *reinterpret_cast<const WrapperDroneCommand*>(
        &_WrapperDroneCommand_default_instance_);
  }
  enum PayloadCase {
    kCommandMessage = 1,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(WrapperDroneCommand& a, WrapperDroneCommand& b) { a.Swap(&b); }
  inline void Swap(WrapperDroneCommand* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WrapperDroneCommand* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WrapperDroneCommand* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WrapperDroneCommand>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WrapperDroneCommand& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WrapperDroneCommand& from) { WrapperDroneCommand::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WrapperDroneCommand* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "WrapperDroneCommand"; }

 protected:
  explicit WrapperDroneCommand(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WrapperDroneCommand(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WrapperDroneCommand& from);
  WrapperDroneCommand(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WrapperDroneCommand&& from) noexcept
      : WrapperDroneCommand(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommandMessageFieldNumber = 1,
  };
  // .DroneCommand command_message = 1;
  bool has_command_message() const;
  private:
  bool _internal_has_command_message() const;

  public:
  void clear_command_message() ;
  const ::DroneCommand& command_message() const;
  [[nodiscard]] ::DroneCommand* PROTOBUF_NULLABLE release_command_message();
  ::DroneCommand* PROTOBUF_NONNULL mutable_command_message();
  void set_allocated_command_message(::DroneCommand* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_command_message(::DroneCommand* PROTOBUF_NULLABLE value);
  ::DroneCommand* PROTOBUF_NULLABLE unsafe_arena_release_command_message();

  private:
  const ::DroneCommand& _internal_command_message() const;
  ::DroneCommand* PROTOBUF_NONNULL _internal_mutable_command_message();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:WrapperDroneCommand)
 private:
  class _Internal;
  void set_has_command_message();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const WrapperDroneCommand& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::DroneCommand* PROTOBUF_NULLABLE command_message_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_5fdrone_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull WrapperDroneCommand_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// WrapperDroneCommand

// .DroneCommand command_message = 1;
inline bool WrapperDroneCommand::has_command_message() const {
  return payload_case() == kCommandMessage;
}
inline bool WrapperDroneCommand::_internal_has_command_message() const {
  return payload_case() == kCommandMessage;
}
inline void WrapperDroneCommand::set_has_command_message() {
  _impl_._oneof_case_[0] = kCommandMessage;
}
inline void WrapperDroneCommand::clear_command_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kCommandMessage) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.command_message_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.command_message_);
    }
    clear_has_payload();
  }
}
inline ::DroneCommand* PROTOBUF_NULLABLE WrapperDroneCommand::release_command_message() {
  // @@protoc_insertion_point(field_release:WrapperDroneCommand.command_message)
  if (payload_case() == kCommandMessage) {
    clear_has_payload();
    auto* temp = _impl_.payload_.command_message_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.command_message_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::DroneCommand& WrapperDroneCommand::_internal_command_message() const {
  return payload_case() == kCommandMessage ? *_impl_.payload_.command_message_ : reinterpret_cast<::DroneCommand&>(::_DroneCommand_default_instance_);
}
inline const ::DroneCommand& WrapperDroneCommand::command_message() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:WrapperDroneCommand.command_message)
  return _internal_command_message();
}
inline ::DroneCommand* PROTOBUF_NULLABLE WrapperDroneCommand::unsafe_arena_release_command_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:WrapperDroneCommand.command_message)
  if (payload_case() == kCommandMessage) {
    clear_has_payload();
    auto* temp = _impl_.payload_.command_message_;
    _impl_.payload_.command_message_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void WrapperDroneCommand::unsafe_arena_set_allocated_command_message(
    ::DroneCommand* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_command_message();
    _impl_.payload_.command_message_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:WrapperDroneCommand.command_message)
}
inline ::DroneCommand* PROTOBUF_NONNULL WrapperDroneCommand::_internal_mutable_command_message() {
  if (payload_case() != kCommandMessage) {
    clear_payload();
    set_has_command_message();
    _impl_.payload_.command_message_ = 
        ::google::protobuf::Message::DefaultConstruct<::DroneCommand>(GetArena());
  }
  return _impl_.payload_.command_message_;
}
inline ::DroneCommand* PROTOBUF_NONNULL WrapperDroneCommand::mutable_command_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::DroneCommand* _msg = _internal_mutable_command_message();
  // @@protoc_insertion_point(field_mutable:WrapperDroneCommand.command_message)
  return _msg;
}

inline bool WrapperDroneCommand::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void WrapperDroneCommand::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline WrapperDroneCommand::PayloadCase WrapperDroneCommand::payload_case() const {
  return WrapperDroneCommand::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// DroneCommand

// string command = 1;
inline void DroneCommand::clear_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.command_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& DroneCommand::command() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DroneCommand.command)
  return _internal_command();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void DroneCommand::set_command(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.command_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DroneCommand.command)
}
inline ::std::string* PROTOBUF_NONNULL DroneCommand::mutable_command()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_command();
  // @@protoc_insertion_point(field_mutable:DroneCommand.command)
  return _s;
}
inline const ::std::string& DroneCommand::_internal_command() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.command_.Get();
}
inline void DroneCommand::_internal_set_command(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.command_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL DroneCommand::_internal_mutable_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.command_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE DroneCommand::release_command() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:DroneCommand.command)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.command_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.command_.Set("", GetArena());
  }
  return released;
}
inline void DroneCommand::set_allocated_command(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.command_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.command_.IsDefault()) {
    _impl_.command_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:DroneCommand.command)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // messages_5fdrone_2eproto_2epb_2eh
