// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_algo.proto

#include "messages_algo.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR Wrapper::Wrapper(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.payload_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct WrapperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WrapperDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WrapperDefaultTypeInternal() {}
  union {
    Wrapper _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WrapperDefaultTypeInternal _Wrapper_default_instance_;
PROTOBUF_CONSTEXPR SignalServerConfigProto::SignalServerConfigProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.rx_heights_)*/{}
  , /*decltype(_impl_.sdf_directory_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.output_file_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.user_terrain_file_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.terrain_background_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.latitude_)*/0
  , /*decltype(_impl_.longitude_)*/0
  , /*decltype(_impl_.tx_height_)*/0
  , /*decltype(_impl_.frequency_mhz_)*/0
  , /*decltype(_impl_.erp_watts_)*/0
  , /*decltype(_impl_.rx_threshold_)*/0
  , /*decltype(_impl_.ground_clutter_)*/0
  , /*decltype(_impl_.terrain_dielectric_)*/0
  , /*decltype(_impl_.terrain_code_)*/0
  , /*decltype(_impl_.climate_code_)*/0
  , /*decltype(_impl_.terrain_conductivity_)*/0
  , /*decltype(_impl_.propagation_model_)*/0
  , /*decltype(_impl_.horizontal_pol_)*/false
  , /*decltype(_impl_.knife_edge_diff_)*/false
  , /*decltype(_impl_.win32_tile_names_)*/false
  , /*decltype(_impl_.debug_mode_)*/false
  , /*decltype(_impl_.metric_units_)*/false
  , /*decltype(_impl_.plot_dbm_)*/false
  , /*decltype(_impl_.resolution_)*/0
  , /*decltype(_impl_.radius_)*/0} {}
struct SignalServerConfigProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SignalServerConfigProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SignalServerConfigProtoDefaultTypeInternal() {}
  union {
    SignalServerConfigProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SignalServerConfigProtoDefaultTypeInternal _SignalServerConfigProto_default_instance_;
PROTOBUF_CONSTEXPR Status::Status(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_status_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StatusDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StatusDefaultTypeInternal() {}
  union {
    Status _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StatusDefaultTypeInternal _Status_default_instance_;
static ::_pb::Metadata file_level_metadata_messages_5falgo_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_messages_5falgo_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_messages_5falgo_2eproto = nullptr;

const uint32_t TableStruct_messages_5falgo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Wrapper, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::Wrapper, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::Wrapper, _impl_.payload_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.sdf_directory_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.output_file_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.user_terrain_file_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.terrain_background_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.latitude_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.longitude_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.tx_height_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.rx_heights_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.frequency_mhz_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.erp_watts_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.rx_threshold_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.horizontal_pol_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.ground_clutter_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.terrain_code_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.terrain_dielectric_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.terrain_conductivity_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.climate_code_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.propagation_model_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.knife_edge_diff_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.win32_tile_names_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.debug_mode_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.metric_units_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.plot_dbm_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.radius_),
  PROTOBUF_FIELD_OFFSET(::SignalServerConfigProto, _impl_.resolution_),
  ~0u,
  ~0u,
  0,
  1,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  2,
  8,
  3,
  5,
  4,
  7,
  6,
  ~0u,
  9,
  10,
  11,
  12,
  13,
  ~0u,
  ~0u,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Status, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Status, _impl_.type_status_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Wrapper)},
  { 9, 40, -1, sizeof(::SignalServerConfigProto)},
  { 65, -1, -1, sizeof(::Status)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_Wrapper_default_instance_._instance,
  &::_SignalServerConfigProto_default_instance_._instance,
  &::_Status_default_instance_._instance,
};

const char descriptor_table_protodef_messages_5falgo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023messages_algo.proto\"i\n\007Wrapper\0228\n\024sign"
  "al_server_config\030\001 \001(\0132\030.SignalServerCon"
  "figProtoH\000\022\031\n\006status\030\002 \001(\0132\007.StatusH\000B\t\n"
  "\007payload\"\236\007\n\027SignalServerConfigProto\022\025\n\r"
  "sdf_directory\030\001 \001(\t\022\023\n\013output_file\030\002 \001(\t"
  "\022\036\n\021user_terrain_file\030\003 \001(\tH\000\210\001\001\022\037\n\022terr"
  "ain_background\030\004 \001(\tH\001\210\001\001\022\020\n\010latitude\030\005 "
  "\001(\001\022\021\n\tlongitude\030\006 \001(\001\022\021\n\ttx_height\030\007 \001("
  "\001\022\022\n\nrx_heights\030\010 \003(\001\022\025\n\rfrequency_mhz\030\t"
  " \001(\001\022\021\n\terp_watts\030\n \001(\001\022\031\n\014rx_threshold\030"
  "\013 \001(\001H\002\210\001\001\022\033\n\016horizontal_pol\030\014 \001(\010H\003\210\001\001\022"
  "\033\n\016ground_clutter\030\r \001(\001H\004\210\001\001\022\031\n\014terrain_"
  "code\030\016 \001(\005H\005\210\001\001\022\037\n\022terrain_dielectric\030\017 "
  "\001(\001H\006\210\001\001\022!\n\024terrain_conductivity\030\020 \001(\001H\007"
  "\210\001\001\022\031\n\014climate_code\030\021 \001(\005H\010\210\001\001\022\031\n\021propag"
  "ation_model\030\022 \001(\005\022\034\n\017knife_edge_diff\030\023 \001"
  "(\010H\t\210\001\001\022\035\n\020win32_tile_names\030\024 \001(\010H\n\210\001\001\022\027"
  "\n\ndebug_mode\030\025 \001(\010H\013\210\001\001\022\031\n\014metric_units\030"
  "\026 \001(\010H\014\210\001\001\022\025\n\010plot_dbm\030\027 \001(\010H\r\210\001\001\022\016\n\006rad"
  "ius\030\030 \001(\001\022\022\n\nresolution\030\031 \001(\005B\024\n\022_user_t"
  "errain_fileB\025\n\023_terrain_backgroundB\017\n\r_r"
  "x_thresholdB\021\n\017_horizontal_polB\021\n\017_groun"
  "d_clutterB\017\n\r_terrain_codeB\025\n\023_terrain_d"
  "ielectricB\027\n\025_terrain_conductivityB\017\n\r_c"
  "limate_codeB\022\n\020_knife_edge_diffB\023\n\021_win3"
  "2_tile_namesB\r\n\013_debug_modeB\017\n\r_metric_u"
  "nitsB\013\n\t_plot_dbm\"\035\n\006Status\022\023\n\013type_stat"
  "us\030\001 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_messages_5falgo_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_messages_5falgo_2eproto = {
    false, false, 1096, descriptor_table_protodef_messages_5falgo_2eproto,
    "messages_algo.proto",
    &descriptor_table_messages_5falgo_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_messages_5falgo_2eproto::offsets,
    file_level_metadata_messages_5falgo_2eproto, file_level_enum_descriptors_messages_5falgo_2eproto,
    file_level_service_descriptors_messages_5falgo_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_messages_5falgo_2eproto_getter() {
  return &descriptor_table_messages_5falgo_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_messages_5falgo_2eproto(&descriptor_table_messages_5falgo_2eproto);

// ===================================================================

class Wrapper::_Internal {
 public:
  static const ::SignalServerConfigProto& signal_server_config(const Wrapper* msg);
  static const ::Status& status(const Wrapper* msg);
};

const ::SignalServerConfigProto&
Wrapper::_Internal::signal_server_config(const Wrapper* msg) {
  return *msg->_impl_.payload_.signal_server_config_;
}
const ::Status&
Wrapper::_Internal::status(const Wrapper* msg) {
  return *msg->_impl_.payload_.status_;
}
void Wrapper::set_allocated_signal_server_config(::SignalServerConfigProto* signal_server_config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (signal_server_config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(signal_server_config);
    if (message_arena != submessage_arena) {
      signal_server_config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, signal_server_config, submessage_arena);
    }
    set_has_signal_server_config();
    _impl_.payload_.signal_server_config_ = signal_server_config;
  }
  // @@protoc_insertion_point(field_set_allocated:Wrapper.signal_server_config)
}
void Wrapper::set_allocated_status(::Status* status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(status);
    if (message_arena != submessage_arena) {
      status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, status, submessage_arena);
    }
    set_has_status();
    _impl_.payload_.status_ = status;
  }
  // @@protoc_insertion_point(field_set_allocated:Wrapper.status)
}
Wrapper::Wrapper(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Wrapper)
}
Wrapper::Wrapper(const Wrapper& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Wrapper* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_payload();
  switch (from.payload_case()) {
    case kSignalServerConfig: {
      _this->_internal_mutable_signal_server_config()->::SignalServerConfigProto::MergeFrom(
          from._internal_signal_server_config());
      break;
    }
    case kStatus: {
      _this->_internal_mutable_status()->::Status::MergeFrom(
          from._internal_status());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:Wrapper)
}

inline void Wrapper::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_payload();
}

Wrapper::~Wrapper() {
  // @@protoc_insertion_point(destructor:Wrapper)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Wrapper::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_payload()) {
    clear_payload();
  }
}

void Wrapper::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Wrapper::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:Wrapper)
  switch (payload_case()) {
    case kSignalServerConfig: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.signal_server_config_;
      }
      break;
    }
    case kStatus: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.status_;
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


void Wrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:Wrapper)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_payload();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Wrapper::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .SignalServerConfigProto signal_server_config = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_signal_server_config(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Status status = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_status(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Wrapper::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Wrapper)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .SignalServerConfigProto signal_server_config = 1;
  if (_internal_has_signal_server_config()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::signal_server_config(this),
        _Internal::signal_server_config(this).GetCachedSize(), target, stream);
  }

  // .Status status = 2;
  if (_internal_has_status()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::status(this),
        _Internal::status(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Wrapper)
  return target;
}

size_t Wrapper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Wrapper)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (payload_case()) {
    // .SignalServerConfigProto signal_server_config = 1;
    case kSignalServerConfig: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.signal_server_config_);
      break;
    }
    // .Status status = 2;
    case kStatus: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.status_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Wrapper::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Wrapper::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Wrapper::GetClassData() const { return &_class_data_; }


void Wrapper::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Wrapper*>(&to_msg);
  auto& from = static_cast<const Wrapper&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Wrapper)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.payload_case()) {
    case kSignalServerConfig: {
      _this->_internal_mutable_signal_server_config()->::SignalServerConfigProto::MergeFrom(
          from._internal_signal_server_config());
      break;
    }
    case kStatus: {
      _this->_internal_mutable_status()->::Status::MergeFrom(
          from._internal_status());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Wrapper::CopyFrom(const Wrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Wrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Wrapper::IsInitialized() const {
  return true;
}

void Wrapper::InternalSwap(Wrapper* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Wrapper::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_5falgo_2eproto_getter, &descriptor_table_messages_5falgo_2eproto_once,
      file_level_metadata_messages_5falgo_2eproto[0]);
}

// ===================================================================

class SignalServerConfigProto::_Internal {
 public:
  using HasBits = decltype(std::declval<SignalServerConfigProto>()._impl_._has_bits_);
  static void set_has_user_terrain_file(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_terrain_background(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_rx_threshold(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_horizontal_pol(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_ground_clutter(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_terrain_code(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_terrain_dielectric(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_terrain_conductivity(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_climate_code(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_knife_edge_diff(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_win32_tile_names(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
  static void set_has_debug_mode(HasBits* has_bits) {
    (*has_bits)[0] |= 2048u;
  }
  static void set_has_metric_units(HasBits* has_bits) {
    (*has_bits)[0] |= 4096u;
  }
  static void set_has_plot_dbm(HasBits* has_bits) {
    (*has_bits)[0] |= 8192u;
  }
};

SignalServerConfigProto::SignalServerConfigProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:SignalServerConfigProto)
}
SignalServerConfigProto::SignalServerConfigProto(const SignalServerConfigProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SignalServerConfigProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.rx_heights_){from._impl_.rx_heights_}
    , decltype(_impl_.sdf_directory_){}
    , decltype(_impl_.output_file_){}
    , decltype(_impl_.user_terrain_file_){}
    , decltype(_impl_.terrain_background_){}
    , decltype(_impl_.latitude_){}
    , decltype(_impl_.longitude_){}
    , decltype(_impl_.tx_height_){}
    , decltype(_impl_.frequency_mhz_){}
    , decltype(_impl_.erp_watts_){}
    , decltype(_impl_.rx_threshold_){}
    , decltype(_impl_.ground_clutter_){}
    , decltype(_impl_.terrain_dielectric_){}
    , decltype(_impl_.terrain_code_){}
    , decltype(_impl_.climate_code_){}
    , decltype(_impl_.terrain_conductivity_){}
    , decltype(_impl_.propagation_model_){}
    , decltype(_impl_.horizontal_pol_){}
    , decltype(_impl_.knife_edge_diff_){}
    , decltype(_impl_.win32_tile_names_){}
    , decltype(_impl_.debug_mode_){}
    , decltype(_impl_.metric_units_){}
    , decltype(_impl_.plot_dbm_){}
    , decltype(_impl_.resolution_){}
    , decltype(_impl_.radius_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.sdf_directory_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sdf_directory_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sdf_directory().empty()) {
    _this->_impl_.sdf_directory_.Set(from._internal_sdf_directory(), 
      _this->GetArenaForAllocation());
  }
  _impl_.output_file_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.output_file_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_output_file().empty()) {
    _this->_impl_.output_file_.Set(from._internal_output_file(), 
      _this->GetArenaForAllocation());
  }
  _impl_.user_terrain_file_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_terrain_file_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_user_terrain_file()) {
    _this->_impl_.user_terrain_file_.Set(from._internal_user_terrain_file(), 
      _this->GetArenaForAllocation());
  }
  _impl_.terrain_background_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.terrain_background_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_terrain_background()) {
    _this->_impl_.terrain_background_.Set(from._internal_terrain_background(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.latitude_, &from._impl_.latitude_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.radius_) -
    reinterpret_cast<char*>(&_impl_.latitude_)) + sizeof(_impl_.radius_));
  // @@protoc_insertion_point(copy_constructor:SignalServerConfigProto)
}

inline void SignalServerConfigProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.rx_heights_){arena}
    , decltype(_impl_.sdf_directory_){}
    , decltype(_impl_.output_file_){}
    , decltype(_impl_.user_terrain_file_){}
    , decltype(_impl_.terrain_background_){}
    , decltype(_impl_.latitude_){0}
    , decltype(_impl_.longitude_){0}
    , decltype(_impl_.tx_height_){0}
    , decltype(_impl_.frequency_mhz_){0}
    , decltype(_impl_.erp_watts_){0}
    , decltype(_impl_.rx_threshold_){0}
    , decltype(_impl_.ground_clutter_){0}
    , decltype(_impl_.terrain_dielectric_){0}
    , decltype(_impl_.terrain_code_){0}
    , decltype(_impl_.climate_code_){0}
    , decltype(_impl_.terrain_conductivity_){0}
    , decltype(_impl_.propagation_model_){0}
    , decltype(_impl_.horizontal_pol_){false}
    , decltype(_impl_.knife_edge_diff_){false}
    , decltype(_impl_.win32_tile_names_){false}
    , decltype(_impl_.debug_mode_){false}
    , decltype(_impl_.metric_units_){false}
    , decltype(_impl_.plot_dbm_){false}
    , decltype(_impl_.resolution_){0}
    , decltype(_impl_.radius_){0}
  };
  _impl_.sdf_directory_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sdf_directory_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.output_file_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.output_file_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.user_terrain_file_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_terrain_file_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.terrain_background_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.terrain_background_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SignalServerConfigProto::~SignalServerConfigProto() {
  // @@protoc_insertion_point(destructor:SignalServerConfigProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SignalServerConfigProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.rx_heights_.~RepeatedField();
  _impl_.sdf_directory_.Destroy();
  _impl_.output_file_.Destroy();
  _impl_.user_terrain_file_.Destroy();
  _impl_.terrain_background_.Destroy();
}

void SignalServerConfigProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SignalServerConfigProto::Clear() {
// @@protoc_insertion_point(message_clear_start:SignalServerConfigProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.rx_heights_.Clear();
  _impl_.sdf_directory_.ClearToEmpty();
  _impl_.output_file_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.user_terrain_file_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.terrain_background_.ClearNonDefaultToEmpty();
    }
  }
  ::memset(&_impl_.latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.erp_watts_) -
      reinterpret_cast<char*>(&_impl_.latitude_)) + sizeof(_impl_.erp_watts_));
  if (cached_has_bits & 0x000000fcu) {
    ::memset(&_impl_.rx_threshold_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.terrain_conductivity_) -
        reinterpret_cast<char*>(&_impl_.rx_threshold_)) + sizeof(_impl_.terrain_conductivity_));
  }
  _impl_.propagation_model_ = 0;
  if (cached_has_bits & 0x00003f00u) {
    ::memset(&_impl_.horizontal_pol_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.plot_dbm_) -
        reinterpret_cast<char*>(&_impl_.horizontal_pol_)) + sizeof(_impl_.plot_dbm_));
  }
  ::memset(&_impl_.resolution_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.radius_) -
      reinterpret_cast<char*>(&_impl_.resolution_)) + sizeof(_impl_.radius_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SignalServerConfigProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string sdf_directory = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_sdf_directory();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "SignalServerConfigProto.sdf_directory"));
        } else
          goto handle_unusual;
        continue;
      // string output_file = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_output_file();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "SignalServerConfigProto.output_file"));
        } else
          goto handle_unusual;
        continue;
      // optional string user_terrain_file = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_user_terrain_file();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "SignalServerConfigProto.user_terrain_file"));
        } else
          goto handle_unusual;
        continue;
      // optional string terrain_background = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_terrain_background();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "SignalServerConfigProto.terrain_background"));
        } else
          goto handle_unusual;
        continue;
      // double latitude = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _impl_.latitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double longitude = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _impl_.longitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double tx_height = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _impl_.tx_height_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated double rx_heights = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_rx_heights(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 65) {
          _internal_add_rx_heights(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double frequency_mhz = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 73)) {
          _impl_.frequency_mhz_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double erp_watts = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 81)) {
          _impl_.erp_watts_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double rx_threshold = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 89)) {
          _Internal::set_has_rx_threshold(&has_bits);
          _impl_.rx_threshold_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional bool horizontal_pol = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _Internal::set_has_horizontal_pol(&has_bits);
          _impl_.horizontal_pol_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional double ground_clutter = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 105)) {
          _Internal::set_has_ground_clutter(&has_bits);
          _impl_.ground_clutter_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional int32 terrain_code = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 112)) {
          _Internal::set_has_terrain_code(&has_bits);
          _impl_.terrain_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional double terrain_dielectric = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 121)) {
          _Internal::set_has_terrain_dielectric(&has_bits);
          _impl_.terrain_dielectric_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double terrain_conductivity = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 129)) {
          _Internal::set_has_terrain_conductivity(&has_bits);
          _impl_.terrain_conductivity_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional int32 climate_code = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 136)) {
          _Internal::set_has_climate_code(&has_bits);
          _impl_.climate_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 propagation_model = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 144)) {
          _impl_.propagation_model_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool knife_edge_diff = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 152)) {
          _Internal::set_has_knife_edge_diff(&has_bits);
          _impl_.knife_edge_diff_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool win32_tile_names = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 160)) {
          _Internal::set_has_win32_tile_names(&has_bits);
          _impl_.win32_tile_names_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool debug_mode = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 168)) {
          _Internal::set_has_debug_mode(&has_bits);
          _impl_.debug_mode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool metric_units = 22;
      case 22:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 176)) {
          _Internal::set_has_metric_units(&has_bits);
          _impl_.metric_units_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool plot_dbm = 23;
      case 23:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 184)) {
          _Internal::set_has_plot_dbm(&has_bits);
          _impl_.plot_dbm_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double radius = 24;
      case 24:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 193)) {
          _impl_.radius_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // int32 resolution = 25;
      case 25:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 200)) {
          _impl_.resolution_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SignalServerConfigProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SignalServerConfigProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string sdf_directory = 1;
  if (!this->_internal_sdf_directory().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sdf_directory().data(), static_cast<int>(this->_internal_sdf_directory().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "SignalServerConfigProto.sdf_directory");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_sdf_directory(), target);
  }

  // string output_file = 2;
  if (!this->_internal_output_file().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_output_file().data(), static_cast<int>(this->_internal_output_file().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "SignalServerConfigProto.output_file");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_output_file(), target);
  }

  // optional string user_terrain_file = 3;
  if (_internal_has_user_terrain_file()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_user_terrain_file().data(), static_cast<int>(this->_internal_user_terrain_file().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "SignalServerConfigProto.user_terrain_file");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_user_terrain_file(), target);
  }

  // optional string terrain_background = 4;
  if (_internal_has_terrain_background()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_terrain_background().data(), static_cast<int>(this->_internal_terrain_background().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "SignalServerConfigProto.terrain_background");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_terrain_background(), target);
  }

  // double latitude = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_latitude = this->_internal_latitude();
  uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_latitude(), target);
  }

  // double longitude = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_longitude = this->_internal_longitude();
  uint64_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_longitude(), target);
  }

  // double tx_height = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_tx_height = this->_internal_tx_height();
  uint64_t raw_tx_height;
  memcpy(&raw_tx_height, &tmp_tx_height, sizeof(tmp_tx_height));
  if (raw_tx_height != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_tx_height(), target);
  }

  // repeated double rx_heights = 8;
  if (this->_internal_rx_heights_size() > 0) {
    target = stream->WriteFixedPacked(8, _internal_rx_heights(), target);
  }

  // double frequency_mhz = 9;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_frequency_mhz = this->_internal_frequency_mhz();
  uint64_t raw_frequency_mhz;
  memcpy(&raw_frequency_mhz, &tmp_frequency_mhz, sizeof(tmp_frequency_mhz));
  if (raw_frequency_mhz != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(9, this->_internal_frequency_mhz(), target);
  }

  // double erp_watts = 10;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_erp_watts = this->_internal_erp_watts();
  uint64_t raw_erp_watts;
  memcpy(&raw_erp_watts, &tmp_erp_watts, sizeof(tmp_erp_watts));
  if (raw_erp_watts != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(10, this->_internal_erp_watts(), target);
  }

  // optional double rx_threshold = 11;
  if (_internal_has_rx_threshold()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(11, this->_internal_rx_threshold(), target);
  }

  // optional bool horizontal_pol = 12;
  if (_internal_has_horizontal_pol()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(12, this->_internal_horizontal_pol(), target);
  }

  // optional double ground_clutter = 13;
  if (_internal_has_ground_clutter()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(13, this->_internal_ground_clutter(), target);
  }

  // optional int32 terrain_code = 14;
  if (_internal_has_terrain_code()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(14, this->_internal_terrain_code(), target);
  }

  // optional double terrain_dielectric = 15;
  if (_internal_has_terrain_dielectric()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(15, this->_internal_terrain_dielectric(), target);
  }

  // optional double terrain_conductivity = 16;
  if (_internal_has_terrain_conductivity()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(16, this->_internal_terrain_conductivity(), target);
  }

  // optional int32 climate_code = 17;
  if (_internal_has_climate_code()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(17, this->_internal_climate_code(), target);
  }

  // int32 propagation_model = 18;
  if (this->_internal_propagation_model() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(18, this->_internal_propagation_model(), target);
  }

  // optional bool knife_edge_diff = 19;
  if (_internal_has_knife_edge_diff()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(19, this->_internal_knife_edge_diff(), target);
  }

  // optional bool win32_tile_names = 20;
  if (_internal_has_win32_tile_names()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(20, this->_internal_win32_tile_names(), target);
  }

  // optional bool debug_mode = 21;
  if (_internal_has_debug_mode()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(21, this->_internal_debug_mode(), target);
  }

  // optional bool metric_units = 22;
  if (_internal_has_metric_units()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(22, this->_internal_metric_units(), target);
  }

  // optional bool plot_dbm = 23;
  if (_internal_has_plot_dbm()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(23, this->_internal_plot_dbm(), target);
  }

  // double radius = 24;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_radius = this->_internal_radius();
  uint64_t raw_radius;
  memcpy(&raw_radius, &tmp_radius, sizeof(tmp_radius));
  if (raw_radius != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(24, this->_internal_radius(), target);
  }

  // int32 resolution = 25;
  if (this->_internal_resolution() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(25, this->_internal_resolution(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SignalServerConfigProto)
  return target;
}

size_t SignalServerConfigProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SignalServerConfigProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double rx_heights = 8;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_rx_heights_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // string sdf_directory = 1;
  if (!this->_internal_sdf_directory().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sdf_directory());
  }

  // string output_file = 2;
  if (!this->_internal_output_file().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_output_file());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string user_terrain_file = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_user_terrain_file());
    }

    // optional string terrain_background = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_terrain_background());
    }

  }
  // double latitude = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_latitude = this->_internal_latitude();
  uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    total_size += 1 + 8;
  }

  // double longitude = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_longitude = this->_internal_longitude();
  uint64_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    total_size += 1 + 8;
  }

  // double tx_height = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_tx_height = this->_internal_tx_height();
  uint64_t raw_tx_height;
  memcpy(&raw_tx_height, &tmp_tx_height, sizeof(tmp_tx_height));
  if (raw_tx_height != 0) {
    total_size += 1 + 8;
  }

  // double frequency_mhz = 9;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_frequency_mhz = this->_internal_frequency_mhz();
  uint64_t raw_frequency_mhz;
  memcpy(&raw_frequency_mhz, &tmp_frequency_mhz, sizeof(tmp_frequency_mhz));
  if (raw_frequency_mhz != 0) {
    total_size += 1 + 8;
  }

  // double erp_watts = 10;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_erp_watts = this->_internal_erp_watts();
  uint64_t raw_erp_watts;
  memcpy(&raw_erp_watts, &tmp_erp_watts, sizeof(tmp_erp_watts));
  if (raw_erp_watts != 0) {
    total_size += 1 + 8;
  }

  if (cached_has_bits & 0x000000fcu) {
    // optional double rx_threshold = 11;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 8;
    }

    // optional double ground_clutter = 13;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 8;
    }

    // optional double terrain_dielectric = 15;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 8;
    }

    // optional int32 terrain_code = 14;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_terrain_code());
    }

    // optional int32 climate_code = 17;
    if (cached_has_bits & 0x00000040u) {
      total_size += 2 +
        ::_pbi::WireFormatLite::Int32Size(
          this->_internal_climate_code());
    }

    // optional double terrain_conductivity = 16;
    if (cached_has_bits & 0x00000080u) {
      total_size += 2 + 8;
    }

  }
  // int32 propagation_model = 18;
  if (this->_internal_propagation_model() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_propagation_model());
  }

  if (cached_has_bits & 0x00003f00u) {
    // optional bool horizontal_pol = 12;
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 + 1;
    }

    // optional bool knife_edge_diff = 19;
    if (cached_has_bits & 0x00000200u) {
      total_size += 2 + 1;
    }

    // optional bool win32_tile_names = 20;
    if (cached_has_bits & 0x00000400u) {
      total_size += 2 + 1;
    }

    // optional bool debug_mode = 21;
    if (cached_has_bits & 0x00000800u) {
      total_size += 2 + 1;
    }

    // optional bool metric_units = 22;
    if (cached_has_bits & 0x00001000u) {
      total_size += 2 + 1;
    }

    // optional bool plot_dbm = 23;
    if (cached_has_bits & 0x00002000u) {
      total_size += 2 + 1;
    }

  }
  // int32 resolution = 25;
  if (this->_internal_resolution() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_resolution());
  }

  // double radius = 24;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_radius = this->_internal_radius();
  uint64_t raw_radius;
  memcpy(&raw_radius, &tmp_radius, sizeof(tmp_radius));
  if (raw_radius != 0) {
    total_size += 2 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SignalServerConfigProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SignalServerConfigProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SignalServerConfigProto::GetClassData() const { return &_class_data_; }


void SignalServerConfigProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SignalServerConfigProto*>(&to_msg);
  auto& from = static_cast<const SignalServerConfigProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SignalServerConfigProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.rx_heights_.MergeFrom(from._impl_.rx_heights_);
  if (!from._internal_sdf_directory().empty()) {
    _this->_internal_set_sdf_directory(from._internal_sdf_directory());
  }
  if (!from._internal_output_file().empty()) {
    _this->_internal_set_output_file(from._internal_output_file());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_user_terrain_file(from._internal_user_terrain_file());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_terrain_background(from._internal_terrain_background());
    }
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_latitude = from._internal_latitude();
  uint64_t raw_latitude;
  memcpy(&raw_latitude, &tmp_latitude, sizeof(tmp_latitude));
  if (raw_latitude != 0) {
    _this->_internal_set_latitude(from._internal_latitude());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_longitude = from._internal_longitude();
  uint64_t raw_longitude;
  memcpy(&raw_longitude, &tmp_longitude, sizeof(tmp_longitude));
  if (raw_longitude != 0) {
    _this->_internal_set_longitude(from._internal_longitude());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_tx_height = from._internal_tx_height();
  uint64_t raw_tx_height;
  memcpy(&raw_tx_height, &tmp_tx_height, sizeof(tmp_tx_height));
  if (raw_tx_height != 0) {
    _this->_internal_set_tx_height(from._internal_tx_height());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_frequency_mhz = from._internal_frequency_mhz();
  uint64_t raw_frequency_mhz;
  memcpy(&raw_frequency_mhz, &tmp_frequency_mhz, sizeof(tmp_frequency_mhz));
  if (raw_frequency_mhz != 0) {
    _this->_internal_set_frequency_mhz(from._internal_frequency_mhz());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_erp_watts = from._internal_erp_watts();
  uint64_t raw_erp_watts;
  memcpy(&raw_erp_watts, &tmp_erp_watts, sizeof(tmp_erp_watts));
  if (raw_erp_watts != 0) {
    _this->_internal_set_erp_watts(from._internal_erp_watts());
  }
  if (cached_has_bits & 0x000000fcu) {
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.rx_threshold_ = from._impl_.rx_threshold_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.ground_clutter_ = from._impl_.ground_clutter_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.terrain_dielectric_ = from._impl_.terrain_dielectric_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.terrain_code_ = from._impl_.terrain_code_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.climate_code_ = from._impl_.climate_code_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.terrain_conductivity_ = from._impl_.terrain_conductivity_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (from._internal_propagation_model() != 0) {
    _this->_internal_set_propagation_model(from._internal_propagation_model());
  }
  if (cached_has_bits & 0x00003f00u) {
    if (cached_has_bits & 0x00000100u) {
      _this->_impl_.horizontal_pol_ = from._impl_.horizontal_pol_;
    }
    if (cached_has_bits & 0x00000200u) {
      _this->_impl_.knife_edge_diff_ = from._impl_.knife_edge_diff_;
    }
    if (cached_has_bits & 0x00000400u) {
      _this->_impl_.win32_tile_names_ = from._impl_.win32_tile_names_;
    }
    if (cached_has_bits & 0x00000800u) {
      _this->_impl_.debug_mode_ = from._impl_.debug_mode_;
    }
    if (cached_has_bits & 0x00001000u) {
      _this->_impl_.metric_units_ = from._impl_.metric_units_;
    }
    if (cached_has_bits & 0x00002000u) {
      _this->_impl_.plot_dbm_ = from._impl_.plot_dbm_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (from._internal_resolution() != 0) {
    _this->_internal_set_resolution(from._internal_resolution());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_radius = from._internal_radius();
  uint64_t raw_radius;
  memcpy(&raw_radius, &tmp_radius, sizeof(tmp_radius));
  if (raw_radius != 0) {
    _this->_internal_set_radius(from._internal_radius());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SignalServerConfigProto::CopyFrom(const SignalServerConfigProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SignalServerConfigProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SignalServerConfigProto::IsInitialized() const {
  return true;
}

void SignalServerConfigProto::InternalSwap(SignalServerConfigProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.rx_heights_.InternalSwap(&other->_impl_.rx_heights_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sdf_directory_, lhs_arena,
      &other->_impl_.sdf_directory_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.output_file_, lhs_arena,
      &other->_impl_.output_file_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.user_terrain_file_, lhs_arena,
      &other->_impl_.user_terrain_file_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.terrain_background_, lhs_arena,
      &other->_impl_.terrain_background_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SignalServerConfigProto, _impl_.radius_)
      + sizeof(SignalServerConfigProto::_impl_.radius_)
      - PROTOBUF_FIELD_OFFSET(SignalServerConfigProto, _impl_.latitude_)>(
          reinterpret_cast<char*>(&_impl_.latitude_),
          reinterpret_cast<char*>(&other->_impl_.latitude_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SignalServerConfigProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_5falgo_2eproto_getter, &descriptor_table_messages_5falgo_2eproto_once,
      file_level_metadata_messages_5falgo_2eproto[1]);
}

// ===================================================================

class Status::_Internal {
 public:
};

Status::Status(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Status)
}
Status::Status(const Status& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Status* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_status_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_status_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_type_status().empty()) {
    _this->_impl_.type_status_.Set(from._internal_type_status(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:Status)
}

inline void Status::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_status_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.type_status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_status_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Status::~Status() {
  // @@protoc_insertion_point(destructor:Status)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Status::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.type_status_.Destroy();
}

void Status::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Status::Clear() {
// @@protoc_insertion_point(message_clear_start:Status)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_status_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Status::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string type_status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_type_status();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Status.type_status"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Status::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Status)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string type_status = 1;
  if (!this->_internal_type_status().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_type_status().data(), static_cast<int>(this->_internal_type_status().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Status.type_status");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_type_status(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Status)
  return target;
}

size_t Status::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Status)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string type_status = 1;
  if (!this->_internal_type_status().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_type_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Status::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Status::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Status::GetClassData() const { return &_class_data_; }


void Status::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Status*>(&to_msg);
  auto& from = static_cast<const Status&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Status)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_type_status().empty()) {
    _this->_internal_set_type_status(from._internal_type_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Status::CopyFrom(const Status& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Status)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Status::IsInitialized() const {
  return true;
}

void Status::InternalSwap(Status* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.type_status_, lhs_arena,
      &other->_impl_.type_status_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Status::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_5falgo_2eproto_getter, &descriptor_table_messages_5falgo_2eproto_once,
      file_level_metadata_messages_5falgo_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Wrapper*
Arena::CreateMaybeMessage< ::Wrapper >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Wrapper >(arena);
}
template<> PROTOBUF_NOINLINE ::SignalServerConfigProto*
Arena::CreateMaybeMessage< ::SignalServerConfigProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SignalServerConfigProto >(arena);
}
template<> PROTOBUF_NOINLINE ::Status*
Arena::CreateMaybeMessage< ::Status >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Status >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
