sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.exclusions=build/**,**/*.pb.cc,**/*.pb.h,Client/proto_bindings/**,**/__pycache__/**
sonar.cfamily.build-wrapper-output=bw-output
