planner_config:
  signal_server_configs:
    - sdf_directory: "/home/ivan/tiles"
      output_file: "cobertura_dbm"
      latitude: 40.29199
      longitude: -3.93978
      tx_height: 5.0
      rx_heights: [1.5]
      frequency_mhz: 900.0
      erp_watts: 20.0
      propagation_model: 1
      radius: 10
      resolution: 1200
      plot_dbm: true  # OPTIONAL
    - sdf_directory: "/home/ivan/tiles"
      output_file: "cobertura_dbm"
      latitude: 40.29228
      longitude: -3.93455
      tx_height: 6.0
      rx_heights: [1.5]
      frequency_mhz: 900.0
      erp_watts: 20.0
      propagation_model: 1
      radius: 10
      resolution: 1200
      plot_dbm: true  # OPTIONAL
  
  drone_data:
    num_drones: 2
    targets:
      - lon: -3.937454
        lat: 40.291579
      - lon: -3.936654
        lat: 40.291579
      - lon: -3.94063
        lat: 40.29256
      - lon: -3.93531
        lat: 40.29138
      - lon: -3.93406
        lat: 40.2932
      - lon: -3.93985
        lat: 40.29078
      - lon: -3.93767
        lat: 40.29276
      - lon: -3.93319
        lat: 40.29224
      - lon: -3.93586
        lat: 40.292
      - lon: -3.93296
        lat: 40.2934
      - lon: -3.93888
        lat: 40.29216
      - lon: -3.94071
        lat: 40.29169
      - lon: -3.93419
        lat: 40.29195
      - lon: -3.93665
        lat: 40.2916
      - lon: -3.93506
        lat: 40.2927
      - lon: -3.93976
        lat: 40.2932
      - lon: -3.93839
        lat: 40.29064

info_planner:
  docker_name: "Planner"
  docker_file: "/home/ivan/repo/I-Drone/I-Drone/Docker/docker-compose.yml"
  module_ip: "127.0.0.1"
  ssh_ip: "127.0.0.1"
  port: "12346"
  user: "ivan"
  key: "/root/.ssh/id_rsa_idrone"

info_drone:
  docker_name: "Drone"
  docker_file: "/home/ivan/repo/I-Drone/I-Drone/Docker/docker-compose.yml"
  module_ip: "127.0.0.1"
  ssh_ip: "127.0.0.1"
  port: "12347"
  user: "ivan"
  key: "/root/.ssh/id_rsa_idrone"

drone_sim: "PX4"
